# Generated by Django 3.1 on 2020-08-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likehome_prk'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeHome',
            new_name='Like',
        ),
    ]
