# Generated by Django 3.1 on 2020-08-17 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200817_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likecom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prk', models.IntegerField(null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
            ],
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
    ]
