# Generated by Django 3.1 on 2020-08-17 06:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200817_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenthome',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/comment'), upload_to=''),
        ),
    ]
