# Generated by Django 3.1 on 2020-09-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_xonkhya_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='xonkhya',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.xonkhya'),
        ),
    ]
