# Generated by Django 3.1 on 2020-09-05 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_xonkhya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='xonkhya',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.xonkhya'),
        ),
    ]
