# Generated by Django 3.1 on 2020-09-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_quiz_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ImageBottom_optional',
        ),
        migrations.RemoveField(
            model_name='post',
            name='background_image_optional',
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.CharField(default='slug', max_length=50),
        ),
    ]
