# Generated by Django 3.1 on 2020-09-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200910_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Profile_Picture',
            field=models.ImageField(upload_to='dp'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='thumbnail',
            field=models.ImageField(default='https://images.freeimages.com/images/premium/previews/2019/20192537-hand-drawn-ink-quill-and-bottle-vector.jpg', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ImageTop_optional',
            field=models.ImageField(default='https://images.freeimages.com/images/premium/previews/2019/20192537-hand-drawn-ink-quill-and-bottle-vector.jpg', upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='thumbnail',
            field=models.ImageField(default='https://images.freeimages.com/images/premium/previews/2019/20192537-hand-drawn-ink-quill-and-bottle-vector.jpg', upload_to='posts'),
        ),
    ]
