# Generated by Django 3.1 on 2020-09-10 09:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200910_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
